### ISSUE TITLE
Library attributions in README

### ISSUE THREAD

**Issue by videlalvaro** [calcinai/php-amqplib-bridge#1]
You README says:

> This library is a polyfill for the PECL::AMQP Extension, using Vadim Zaliva's php-amqplib.

In the last five years the library hasn't received a single commit by Vadim Zaliva's, even more the library has been completely refactored, we added support for `AMQP 0.9.1` plus improved performance, added tests and many more things. I think having that wording in your README is a bit disrespectful for current maintainers and contributors: https://github.com/videlalvaro/php-amqplib/graphs/contributors

**Comment by calcinai** [comment]
Hey, sorry about that - it was an honest mistake as to what I thought the origin of the library was (had seen it referred to as that before).  Will update asap.

**Comment by videlalvaro** [comment]
I think just having the name of the library is enough, since there are many contributors

**Comment by calcinai** [comment]
Sorted.

**Comment by videlalvaro** [comment]
thanks
