### ISSUE TITLE
Fixed 2.5.* amqplib version

### ISSUE THREAD

**Issue by m4rcinkowski** [calcinai/php-amqplib-bridge#5]
I'm trying to use a library that's built on your bridge under the hood. The problem is that the application itself already uses an ampqllib ^2.6 dependency which conflicts with your __fixed__ **2.5.*** version.

Could you bump the version or at least use a [caret versioning](https://getcomposer.org/doc/articles/versions.md#caret)?

**Comment by calcinai** [comment]
Oh sorry about that. I'll sort it out today

**Comment by calcinai** [comment]
Done!  Not sure why it wasn't like this in the first place..
